package com.juanmuscaria.blockheads.old.jna.enet.structures;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : ./enet/protocol.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ENetProtocolAcknowledge extends Structure {
  /**
   * C type : ENetProtocolCommandHeader
   */
  public ENetProtocolCommandHeader header;
  /**
   * C type : enet_uint16
   */
  public short receivedReliableSequenceNumber;
  /**
   * C type : enet_uint16
   */
  public short receivedSentTime;

  public ENetProtocolAcknowledge() {
    super();
  }

  /**
   * @param header                         C type : ENetProtocolCommandHeader<br>
   * @param receivedReliableSequenceNumber C type : enet_uint16<br>
   * @param receivedSentTime               C type : enet_uint16
   */
  public ENetProtocolAcknowledge(ENetProtocolCommandHeader header, short receivedReliableSequenceNumber, short receivedSentTime) {
    super();
    this.header = header;
    this.receivedReliableSequenceNumber = receivedReliableSequenceNumber;
    this.receivedSentTime = receivedSentTime;
  }

  public ENetProtocolAcknowledge(Pointer peer) {
    super(peer);
  }

  protected List<String> getFieldOrder() {
    return Arrays.asList("header", "receivedReliableSequenceNumber", "receivedSentTime");
  }

  public static class ByReference extends ENetProtocolAcknowledge implements Structure.ByReference {

  }

  public static class ByValue extends ENetProtocolAcknowledge implements Structure.ByValue {

  }
}
