// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct _ENetProtocolThrottleConfigure {
 *     ENetProtocolCommandHeader header;
 *     enet_uint32 packetThrottleInterval;
 *     enet_uint32 packetThrottleAcceleration;
 *     enet_uint32 packetThrottleDeceleration;
 * };
 * }
 */
public class _ENetProtocolThrottleConfigure {

    public static MemoryLayout $LAYOUT() {
        return constants$87.const$0;
    }
    public static MemorySegment header$slice(MemorySegment seg) {
        return seg.asSlice(0, 4);
    }
    public static VarHandle packetThrottleInterval$VH() {
        return constants$87.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enet_uint32 packetThrottleInterval;
     * }
     */
    public static int packetThrottleInterval$get(MemorySegment seg) {
        return (int)constants$87.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enet_uint32 packetThrottleInterval;
     * }
     */
    public static void packetThrottleInterval$set(MemorySegment seg, int x) {
        constants$87.const$1.set(seg, x);
    }
    public static int packetThrottleInterval$get(MemorySegment seg, long index) {
        return (int)constants$87.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void packetThrottleInterval$set(MemorySegment seg, long index, int x) {
        constants$87.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle packetThrottleAcceleration$VH() {
        return constants$87.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enet_uint32 packetThrottleAcceleration;
     * }
     */
    public static int packetThrottleAcceleration$get(MemorySegment seg) {
        return (int)constants$87.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enet_uint32 packetThrottleAcceleration;
     * }
     */
    public static void packetThrottleAcceleration$set(MemorySegment seg, int x) {
        constants$87.const$2.set(seg, x);
    }
    public static int packetThrottleAcceleration$get(MemorySegment seg, long index) {
        return (int)constants$87.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void packetThrottleAcceleration$set(MemorySegment seg, long index, int x) {
        constants$87.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle packetThrottleDeceleration$VH() {
        return constants$87.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enet_uint32 packetThrottleDeceleration;
     * }
     */
    public static int packetThrottleDeceleration$get(MemorySegment seg) {
        return (int)constants$87.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enet_uint32 packetThrottleDeceleration;
     * }
     */
    public static void packetThrottleDeceleration$set(MemorySegment seg, int x) {
        constants$87.const$3.set(seg, x);
    }
    public static int packetThrottleDeceleration$get(MemorySegment seg, long index) {
        return (int)constants$87.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void packetThrottleDeceleration$set(MemorySegment seg, long index, int x) {
        constants$87.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


