// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.Arena;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;
import java.lang.invoke.VarHandle;

/**
 * {@snippet :
 * struct _ENetProtocolBandwidthLimit {
 *     ENetProtocolCommandHeader header;
 *     enet_uint32 incomingBandwidth;
 *     enet_uint32 outgoingBandwidth;
 * };
 * }
 */
public class _ENetProtocolBandwidthLimit {

    public static MemoryLayout $LAYOUT() {
      return constants$6.const$1;
    }
    public static MemorySegment header$slice(MemorySegment seg) {
        return seg.asSlice(0, 4);
    }
    public static VarHandle incomingBandwidth$VH() {
      return constants$6.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enet_uint32 incomingBandwidth;
     * }
     */
    public static int incomingBandwidth$get(MemorySegment seg) {
      return (int) constants$6.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enet_uint32 incomingBandwidth;
     * }
     */
    public static void incomingBandwidth$set(MemorySegment seg, int x) {
      constants$6.const$2.set(seg, x);
    }
    public static int incomingBandwidth$get(MemorySegment seg, long index) {
      return (int) constants$6.const$2.get(seg.asSlice(index * sizeof()));
    }
    public static void incomingBandwidth$set(MemorySegment seg, long index, int x) {
      constants$6.const$2.set(seg.asSlice(index * sizeof()), x);
    }
    public static VarHandle outgoingBandwidth$VH() {
      return constants$6.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enet_uint32 outgoingBandwidth;
     * }
     */
    public static int outgoingBandwidth$get(MemorySegment seg) {
      return (int) constants$6.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enet_uint32 outgoingBandwidth;
     * }
     */
    public static void outgoingBandwidth$set(MemorySegment seg, int x) {
      constants$6.const$3.set(seg, x);
    }
    public static int outgoingBandwidth$get(MemorySegment seg, long index) {
      return (int) constants$6.const$3.get(seg.asSlice(index * sizeof()));
    }
    public static void outgoingBandwidth$set(MemorySegment seg, long index, int x) {
      constants$6.const$3.set(seg.asSlice(index * sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


