// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct _ENetProtocolCommandHeader {
 *     enet_uint8 command;
 *     enet_uint8 channelID;
 *     enet_uint16 reliableSequenceNumber;
 * };
 * }
 */
public class _ENetProtocolCommandHeader {

    public static MemoryLayout $LAYOUT() {
        return constants$80.const$5;
    }
    public static VarHandle command$VH() {
        return constants$81.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enet_uint8 command;
     * }
     */
    public static byte command$get(MemorySegment seg) {
        return (byte)constants$81.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enet_uint8 command;
     * }
     */
    public static void command$set(MemorySegment seg, byte x) {
        constants$81.const$0.set(seg, x);
    }
    public static byte command$get(MemorySegment seg, long index) {
        return (byte)constants$81.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void command$set(MemorySegment seg, long index, byte x) {
        constants$81.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle channelID$VH() {
        return constants$81.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enet_uint8 channelID;
     * }
     */
    public static byte channelID$get(MemorySegment seg) {
        return (byte)constants$81.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enet_uint8 channelID;
     * }
     */
    public static void channelID$set(MemorySegment seg, byte x) {
        constants$81.const$1.set(seg, x);
    }
    public static byte channelID$get(MemorySegment seg, long index) {
        return (byte)constants$81.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void channelID$set(MemorySegment seg, long index, byte x) {
        constants$81.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle reliableSequenceNumber$VH() {
        return constants$81.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enet_uint16 reliableSequenceNumber;
     * }
     */
    public static short reliableSequenceNumber$get(MemorySegment seg) {
        return (short)constants$81.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enet_uint16 reliableSequenceNumber;
     * }
     */
    public static void reliableSequenceNumber$set(MemorySegment seg, short x) {
        constants$81.const$2.set(seg, x);
    }
    public static short reliableSequenceNumber$get(MemorySegment seg, long index) {
        return (short)constants$81.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void reliableSequenceNumber$set(MemorySegment seg, long index, short x) {
        constants$81.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


