// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct _ENetProtocolHeader {
 *     enet_uint16 peerID;
 *     enet_uint16 sentTime;
 * };
 * }
 */
public class _ENetProtocolHeader {

    public static MemoryLayout $LAYOUT() {
        return constants$80.const$2;
    }
    public static VarHandle peerID$VH() {
        return constants$80.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enet_uint16 peerID;
     * }
     */
    public static short peerID$get(MemorySegment seg) {
        return (short)constants$80.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enet_uint16 peerID;
     * }
     */
    public static void peerID$set(MemorySegment seg, short x) {
        constants$80.const$3.set(seg, x);
    }
    public static short peerID$get(MemorySegment seg, long index) {
        return (short)constants$80.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void peerID$set(MemorySegment seg, long index, short x) {
        constants$80.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle sentTime$VH() {
        return constants$80.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enet_uint16 sentTime;
     * }
     */
    public static short sentTime$get(MemorySegment seg) {
        return (short)constants$80.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enet_uint16 sentTime;
     * }
     */
    public static void sentTime$set(MemorySegment seg, short x) {
        constants$80.const$4.set(seg, x);
    }
    public static short sentTime$get(MemorySegment seg, long index) {
        return (short)constants$80.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void sentTime$set(MemorySegment seg, long index, short x) {
        constants$80.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


