// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct _ENetListNode {
 *     struct _ENetListNode* next;
 *     struct _ENetListNode* previous;
 * };
 * }
 */
public class _ENetListNode {

    public static MemoryLayout $LAYOUT() {
        return constants$90.const$5;
    }
    public static VarHandle next$VH() {
        return constants$91.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct _ENetListNode* next;
     * }
     */
    public static MemorySegment next$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$91.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct _ENetListNode* next;
     * }
     */
    public static void next$set(MemorySegment seg, MemorySegment x) {
        constants$91.const$0.set(seg, x);
    }
    public static MemorySegment next$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$91.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void next$set(MemorySegment seg, long index, MemorySegment x) {
        constants$91.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle previous$VH() {
        return constants$91.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct _ENetListNode* previous;
     * }
     */
    public static MemorySegment previous$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$91.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct _ENetListNode* previous;
     * }
     */
    public static void previous$set(MemorySegment seg, MemorySegment x) {
        constants$91.const$1.set(seg, x);
    }
    public static MemorySegment previous$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$91.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void previous$set(MemorySegment seg, long index, MemorySegment x) {
        constants$91.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


