// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct _ENetProtocolBandwidthLimit {
 *     ENetProtocolCommandHeader header;
 *     enet_uint32 incomingBandwidth;
 *     enet_uint32 outgoingBandwidth;
 * };
 * }
 */
public class _ENetProtocolBandwidthLimit {

    public static MemoryLayout $LAYOUT() {
        return constants$86.const$3;
    }
    public static MemorySegment header$slice(MemorySegment seg) {
        return seg.asSlice(0, 4);
    }
    public static VarHandle incomingBandwidth$VH() {
        return constants$86.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enet_uint32 incomingBandwidth;
     * }
     */
    public static int incomingBandwidth$get(MemorySegment seg) {
        return (int)constants$86.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enet_uint32 incomingBandwidth;
     * }
     */
    public static void incomingBandwidth$set(MemorySegment seg, int x) {
        constants$86.const$4.set(seg, x);
    }
    public static int incomingBandwidth$get(MemorySegment seg, long index) {
        return (int)constants$86.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void incomingBandwidth$set(MemorySegment seg, long index, int x) {
        constants$86.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle outgoingBandwidth$VH() {
        return constants$86.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enet_uint32 outgoingBandwidth;
     * }
     */
    public static int outgoingBandwidth$get(MemorySegment seg) {
        return (int)constants$86.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enet_uint32 outgoingBandwidth;
     * }
     */
    public static void outgoingBandwidth$set(MemorySegment seg, int x) {
        constants$86.const$5.set(seg, x);
    }
    public static int outgoingBandwidth$get(MemorySegment seg, long index) {
        return (int)constants$86.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void outgoingBandwidth$set(MemorySegment seg, long index, int x) {
        constants$86.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


