// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct _ENetAcknowledgement {
 *     ENetListNode acknowledgementList;
 *     enet_uint32 sentTime;
 *     ENetProtocol command;
 * };
 * }
 */
public class _ENetAcknowledgement {

    public static MemoryLayout $LAYOUT() {
        return constants$16.const$5;
    }
    public static MemorySegment acknowledgementList$slice(MemorySegment seg) {
        return seg.asSlice(0, 16);
    }
    public static VarHandle sentTime$VH() {
        return constants$17.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enet_uint32 sentTime;
     * }
     */
    public static int sentTime$get(MemorySegment seg) {
        return (int) constants$17.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enet_uint32 sentTime;
     * }
     */
    public static void sentTime$set(MemorySegment seg, int x) {
        constants$17.const$0.set(seg, x);
    }
    public static int sentTime$get(MemorySegment seg, long index) {
        return (int) constants$17.const$0.get(seg.asSlice(index * sizeof()));
    }
    public static void sentTime$set(MemorySegment seg, long index, int x) {
        constants$17.const$0.set(seg.asSlice(index * sizeof()), x);
    }
    public static MemorySegment command$slice(MemorySegment seg) {
        return seg.asSlice(20, 48);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


