// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.MemoryLayout;
import java.lang.foreign.StructLayout;
import java.lang.invoke.VarHandle;

final class constants$29 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$29() {}

  static final VarHandle const$0 = constants$21.const$0.varHandle(MemoryLayout.PathElement.groupElement("reserved"));
  static final VarHandle const$1 = constants$21.const$0.varHandle(MemoryLayout.PathElement.groupElement("incomingUnsequencedGroup"));
  static final VarHandle const$2 = constants$21.const$0.varHandle(MemoryLayout.PathElement.groupElement("outgoingUnsequencedGroup"));
  static final VarHandle const$3 = constants$21.const$0.varHandle(MemoryLayout.PathElement.groupElement("eventData"));
  static final VarHandle const$4 = constants$21.const$0.varHandle(MemoryLayout.PathElement.groupElement("totalWaitingData"));
  static final StructLayout const$5 = MemoryLayout.structLayout(
    RuntimeHelper.POINTER.withName("context"),
    RuntimeHelper.POINTER.withName("compress"),
    RuntimeHelper.POINTER.withName("decompress"),
    RuntimeHelper.POINTER.withName("destroy")
  ).withName("_ENetCompressor");
}


