// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$21 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$21() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(3, JAVA_SHORT).withName("__x"),
        MemoryLayout.sequenceLayout(3, JAVA_SHORT).withName("__old_x"),
        JAVA_SHORT.withName("__c"),
        JAVA_SHORT.withName("__init"),
        JAVA_LONG.withName("__a")
    ).withName("drand48_data");
    static final VarHandle const$1 = constants$21.const$0.varHandle(MemoryLayout.PathElement.groupElement("__c"));
    static final VarHandle const$2 = constants$21.const$0.varHandle(MemoryLayout.PathElement.groupElement("__init"));
    static final VarHandle const$3 = constants$21.const$0.varHandle(MemoryLayout.PathElement.groupElement("__a"));
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "drand48_r",
        constants$17.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "erand48_r",
        constants$21.const$5
    );
}


