// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_BYTE;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$53 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$53() {}

  static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
    "enet_range_coder_destroy",
    constants$11.const$1
  );
  static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
    "enet_range_coder_compress",
    constants$30.const$1
  );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
      "enet_range_coder_decompress",
      constants$30.const$5
    );
  static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_LONG,
    JAVA_BYTE
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
      "enet_protocol_command_size",
        constants$53.const$3
    );
  static final MemorySegment const$5 = MemorySegment.ofAddress(0L);
}


