// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$84 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$84() {}
    static final VarHandle const$0 = constants$82.const$0.varHandle(MemoryLayout.PathElement.groupElement("connectID"));
    static final VarHandle const$1 = constants$82.const$0.varHandle(MemoryLayout.PathElement.groupElement("data"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("command"),
            JAVA_BYTE.withName("channelID"),
            JAVA_SHORT.withByteAlignment(1).withName("reliableSequenceNumber")
        ).withName("header"),
        JAVA_SHORT.withByteAlignment(1).withName("outgoingPeerID"),
        JAVA_BYTE.withName("incomingSessionID"),
        JAVA_BYTE.withName("outgoingSessionID"),
        JAVA_INT.withByteAlignment(1).withName("mtu"),
        JAVA_INT.withByteAlignment(1).withName("windowSize"),
        JAVA_INT.withByteAlignment(1).withName("channelCount"),
        JAVA_INT.withByteAlignment(1).withName("incomingBandwidth"),
        JAVA_INT.withByteAlignment(1).withName("outgoingBandwidth"),
        JAVA_INT.withByteAlignment(1).withName("packetThrottleInterval"),
        JAVA_INT.withByteAlignment(1).withName("packetThrottleAcceleration"),
        JAVA_INT.withByteAlignment(1).withName("packetThrottleDeceleration"),
        JAVA_INT.withByteAlignment(1).withName("connectID")
    ).withName("_ENetProtocolVerifyConnect");
    static final VarHandle const$3 = constants$84.const$2.varHandle(MemoryLayout.PathElement.groupElement("outgoingPeerID"));
    static final VarHandle const$4 = constants$84.const$2.varHandle(MemoryLayout.PathElement.groupElement("incomingSessionID"));
    static final VarHandle const$5 = constants$84.const$2.varHandle(MemoryLayout.PathElement.groupElement("outgoingSessionID"));
}


