// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;

final class constants$76 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$76() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "acct",
        constants$2.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getusershell",
        constants$72.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "endusershell",
        constants$26.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "setusershell",
        constants$26.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "daemon",
        constants$46.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "chroot",
        constants$2.const$0
    );
}


