// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

final class constants$85 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$85() {}
    static final VarHandle const$0 = constants$84.const$2.varHandle(MemoryLayout.PathElement.groupElement("mtu"));
    static final VarHandle const$1 = constants$84.const$2.varHandle(MemoryLayout.PathElement.groupElement("windowSize"));
    static final VarHandle const$2 = constants$84.const$2.varHandle(MemoryLayout.PathElement.groupElement("channelCount"));
    static final VarHandle const$3 = constants$84.const$2.varHandle(MemoryLayout.PathElement.groupElement("incomingBandwidth"));
    static final VarHandle const$4 = constants$84.const$2.varHandle(MemoryLayout.PathElement.groupElement("outgoingBandwidth"));
    static final VarHandle const$5 = constants$84.const$2.varHandle(MemoryLayout.PathElement.groupElement("packetThrottleInterval"));
}


