// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$41 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$41() {}
    static final VarHandle const$0 = constants$40.const$5.varHandle(MemoryLayout.PathElement.groupElement("cmsg_len"));
    static final VarHandle const$1 = constants$40.const$5.varHandle(MemoryLayout.PathElement.groupElement("cmsg_level"));
    static final VarHandle const$2 = constants$40.const$5.varHandle(MemoryLayout.PathElement.groupElement("cmsg_type"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "__cmsg_nxthdr",
        constants$30.const$2
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(16, JAVA_LONG).withName("fds_bits")
    ).withName("");
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(__kernel_sighandler_t.class, "apply", constants$15.const$0);
}


