// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemoryLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;

final class constants$14 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$14() {}

  static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid();
  static final MethodHandle const$1 = RuntimeHelper.upcallHandle(_ENetCallbacks.no_memory.class, "apply", constants$14.const$0);
  static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
    constants$14.const$0
  );
  static final VarHandle const$3 = constants$12.const$4.varHandle(MemoryLayout.PathElement.groupElement("no_memory"));
  static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
    "enet_malloc",
    constants$12.const$5
  );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
      "enet_free",
      constants$11.const$1
    );
}


