// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$64 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$64() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandleVariadic(
        "execl",
        constants$17.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "execvp",
        constants$17.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandleVariadic(
        "execlp",
        constants$17.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "nice",
        constants$23.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "_exit",
        constants$15.const$0
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "pathconf",
        constants$64.const$5
    );
}


