// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$20 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$20() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "mrand48",
        constants$1.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "jrand48",
        constants$2.const$2
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        JAVA_LONG
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "srand48",
        constants$20.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "seed48",
        constants$15.const$4
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "lcong48",
        constants$20.const$5
    );
}


