// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$41 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$41() {}

  static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
    "enet_socket_accept",
    constants$39.const$0
  );
  static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
    "enet_socket_connect",
    constants$39.const$0
  );
  static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
    JAVA_INT,
    RuntimeHelper.POINTER,
    RuntimeHelper.POINTER,
    JAVA_LONG
  );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
      "enet_socket_send",
      constants$41.const$2
    );
  static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
    "enet_socket_receive",
    constants$41.const$2
    );
  static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
    JAVA_INT,
    RuntimeHelper.POINTER,
    JAVA_INT
  );
  static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
    "enet_socket_wait",
    constants$41.const$5
  );
}


