// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

final class constants$30 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$30() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "mkdtemp",
        constants$15.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "system",
        constants$2.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "realpath",
        constants$30.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(__compar_fn_t.class, "apply", constants$17.const$2);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$17.const$2
    );
}


