// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$87 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$87() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("command"),
            JAVA_BYTE.withName("channelID"),
            JAVA_SHORT.withByteAlignment(1).withName("reliableSequenceNumber")
        ).withName("header"),
        JAVA_INT.withByteAlignment(1).withName("packetThrottleInterval"),
        JAVA_INT.withByteAlignment(1).withName("packetThrottleAcceleration"),
        JAVA_INT.withByteAlignment(1).withName("packetThrottleDeceleration")
    ).withName("_ENetProtocolThrottleConfigure");
    static final VarHandle const$1 = constants$87.const$0.varHandle(MemoryLayout.PathElement.groupElement("packetThrottleInterval"));
    static final VarHandle const$2 = constants$87.const$0.varHandle(MemoryLayout.PathElement.groupElement("packetThrottleAcceleration"));
    static final VarHandle const$3 = constants$87.const$0.varHandle(MemoryLayout.PathElement.groupElement("packetThrottleDeceleration"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("command"),
            JAVA_BYTE.withName("channelID"),
            JAVA_SHORT.withByteAlignment(1).withName("reliableSequenceNumber")
        ).withName("header"),
        JAVA_INT.withByteAlignment(1).withName("data")
    ).withName("_ENetProtocolDisconnect");
    static final VarHandle const$5 = constants$87.const$4.varHandle(MemoryLayout.PathElement.groupElement("data"));
}


