// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.StructLayout;
import java.lang.invoke.MethodHandle;

final class constants$11 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$11() {}

  static final StructLayout const$0 = MemoryLayout.structLayout(
    MemoryLayout.structLayout(
      RuntimeHelper.POINTER.withName("next"),
      RuntimeHelper.POINTER.withName("previous")
    ).withName("sentinel")
  ).withName("_ENetList");
  static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
    RuntimeHelper.POINTER
  );
  static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
    "enet_list_clear",
    constants$11.const$1
  );
  static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
    RuntimeHelper.POINTER,
    RuntimeHelper.POINTER
  );
  static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
    "enet_list_insert",
    constants$11.const$3
  );
  static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
    RuntimeHelper.POINTER
  );
  static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
    "enet_list_remove",
    constants$11.const$5
  );
}


