// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

final class constants$11 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$11() {}
    static final VarHandle const$0 = constants$10.const$0.varHandle(MemoryLayout.PathElement.groupElement("__pad4"));
    static final VarHandle const$1 = constants$10.const$0.varHandle(MemoryLayout.PathElement.groupElement("__cur_writer"));
    static final VarHandle const$2 = constants$10.const$0.varHandle(MemoryLayout.PathElement.groupElement("__shared"));
    static final VarHandle const$3 = constants$10.const$0.varHandle(MemoryLayout.PathElement.groupElement("__rwelision"));
    static final VarHandle const$4 = constants$10.const$0.varHandle(MemoryLayout.PathElement.groupElement("__pad2"));
    static final VarHandle const$5 = constants$10.const$0.varHandle(MemoryLayout.PathElement.groupElement("__flags"));
}


