// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.StructLayout;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}

  static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
    RuntimeHelper.POINTER,
    RuntimeHelper.POINTER,
    RuntimeHelper.POINTER
  );
  static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
    "enet_list_move",
    constants$12.const$0
  );
  static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_LONG,
    RuntimeHelper.POINTER
  );
  static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
    "enet_list_size",
    constants$12.const$2
  );
  static final StructLayout const$4 = MemoryLayout.structLayout(
    RuntimeHelper.POINTER.withName("malloc"),
    RuntimeHelper.POINTER.withName("free"),
    RuntimeHelper.POINTER.withName("no_memory")
  ).withName("_ENetCallbacks");
  static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
    JAVA_LONG
  );
}


