// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$94 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$94() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "enet_malloc",
        constants$4.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "enet_free",
        constants$20.const$5
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("host"),
        JAVA_SHORT.withName("port"),
        MemoryLayout.paddingLayout(2)
    ).withName("_ENetAddress");
    static final VarHandle const$3 = constants$94.const$2.varHandle(MemoryLayout.PathElement.groupElement("host"));
    static final VarHandle const$4 = constants$94.const$2.varHandle(MemoryLayout.PathElement.groupElement("port"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(ENetPacketFreeCallback.class, "apply", constants$20.const$5);
}


