// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;

final class constants$68 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$68() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "getgroups",
        constants$17.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "setuid",
        constants$23.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "setreuid",
        constants$46.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "seteuid",
        constants$23.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "setgid",
        constants$23.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "setregid",
        constants$46.const$5
    );
}


