// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
final class constants$42 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$42() {}

  static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
    JAVA_INT,
    JAVA_INT,
    JAVA_INT
  );
  static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
    "enet_socket_set_option",
    constants$42.const$0
    );
  static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
    JAVA_INT,
    JAVA_INT,
    RuntimeHelper.POINTER
  );
  static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
    "enet_socket_get_option",
    constants$42.const$2
  );
  static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
    "enet_socket_shutdown",
    constants$40.const$4
  );
  static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
    "enet_socket_destroy",
    constants$39.const$5
  );
}


