// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$129 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$129() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_SHORT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "enet_peer_queue_acknowledgement",
        constants$129.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "enet_peer_dispatch_incoming_unreliable_commands",
        constants$129.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "enet_peer_dispatch_incoming_reliable_commands",
        constants$129.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "enet_peer_on_connect",
        constants$20.const$5
    );
}


