// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

final class constants$107 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$107() {}
    static final VarHandle const$0 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("highestRoundTripTimeVariance"));
    static final VarHandle const$1 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("roundTripTime"));
    static final VarHandle const$2 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("roundTripTimeVariance"));
    static final VarHandle const$3 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("mtu"));
    static final VarHandle const$4 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("windowSize"));
    static final VarHandle const$5 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("reliableDataInTransit"));
}


