// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "strtouq",
        constants$3.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "strtoll",
        constants$3.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "strtoull",
        constants$3.const$2
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "l64a",
        constants$4.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "a64l",
        constants$2.const$2
    );
}


