// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.MemoryLayout;
import java.lang.invoke.VarHandle;

final class constants$5 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$5() {}

  static final VarHandle const$0 = constants$4.const$0.varHandle(MemoryLayout.PathElement.groupElement("channelCount"));
  static final VarHandle const$1 = constants$4.const$0.varHandle(MemoryLayout.PathElement.groupElement("incomingBandwidth"));
  static final VarHandle const$2 = constants$4.const$0.varHandle(MemoryLayout.PathElement.groupElement("outgoingBandwidth"));
  static final VarHandle const$3 = constants$4.const$0.varHandle(MemoryLayout.PathElement.groupElement("packetThrottleInterval"));
  static final VarHandle const$4 = constants$4.const$0.varHandle(MemoryLayout.PathElement.groupElement("packetThrottleAcceleration"));
  static final VarHandle const$5 = constants$4.const$0.varHandle(MemoryLayout.PathElement.groupElement("packetThrottleDeceleration"));
}


