// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;

final class constants$119 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$119() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "enet_socket_get_address",
        constants$17.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "enet_socket_listen",
        constants$46.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "enet_socket_accept",
        constants$17.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "enet_socket_connect",
        constants$17.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "enet_socket_send",
        constants$57.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "enet_socket_receive",
        constants$57.const$0
    );
}


