// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;

final class constants$62 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$62() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "chdir",
        constants$2.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "fchdir",
        constants$23.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getcwd",
        constants$24.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getwd",
        constants$15.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "dup",
        constants$23.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "dup2",
        constants$46.const$5
    );
}


