// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$19 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$19() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "rand_r",
        constants$2.const$0
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_DOUBLE);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "drand48",
        constants$19.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "erand48",
        constants$1.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "lrand48",
        constants$1.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "nrand48",
        constants$2.const$2
    );
}


