// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;

final class constants$77 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$77() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "getpass",
        constants$15.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "fsync",
        constants$23.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "gethostid",
        constants$1.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "sync",
        constants$26.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "getpagesize",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getdtablesize",
        constants$18.const$3
    );
}


