// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
final class constants$40 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$40() {}

  static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
    JAVA_INT
  );
  static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
    "enet_socket_create",
    constants$40.const$0
  );
  static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
    "enet_socket_bind",
    constants$39.const$0
  );
  static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
    "enet_socket_get_address",
    constants$39.const$0
  );
  static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
    JAVA_INT,
    JAVA_INT
  );
  static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
    "enet_socket_listen",
    constants$40.const$4
  );
}


