// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$116 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$116() {}
    static final VarHandle const$0 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("bandwidthLimitedPeers"));
    static final VarHandle const$1 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("duplicatePeers"));
    static final VarHandle const$2 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("maximumPacketSize"));
    static final VarHandle const$3 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("maximumWaitingData"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("peer"),
        JAVA_BYTE.withName("channelID"),
        MemoryLayout.paddingLayout(3),
        JAVA_INT.withName("data"),
        RuntimeHelper.POINTER.withName("packet")
    ).withName("_ENetEvent");
    static final VarHandle const$5 = constants$116.const$4.varHandle(MemoryLayout.PathElement.groupElement("type"));
}


