// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.MemoryLayout;
import java.lang.invoke.VarHandle;

final class constants$23 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$23() {}

  static final VarHandle const$0 = constants$21.const$0.varHandle(MemoryLayout.PathElement.groupElement("outgoingBandwidth"));
  static final VarHandle const$1 = constants$21.const$0.varHandle(MemoryLayout.PathElement.groupElement("incomingBandwidthThrottleEpoch"));
  static final VarHandle const$2 = constants$21.const$0.varHandle(MemoryLayout.PathElement.groupElement("outgoingBandwidthThrottleEpoch"));
  static final VarHandle const$3 = constants$21.const$0.varHandle(MemoryLayout.PathElement.groupElement("incomingDataTotal"));
  static final VarHandle const$4 = constants$21.const$0.varHandle(MemoryLayout.PathElement.groupElement("outgoingDataTotal"));
  static final VarHandle const$5 = constants$21.const$0.varHandle(MemoryLayout.PathElement.groupElement("lastSendTime"));
}


