// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$123 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$123() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "enet_host_destroy",
        constants$20.const$5
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "enet_host_connect",
        constants$123.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "enet_host_check_events",
        constants$17.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "enet_host_service",
        constants$28.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "enet_host_flush",
        constants$20.const$5
    );
}


