// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$18 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$18() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "initstate_r",
        constants$18.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "setstate_r",
        constants$17.const$2
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "rand",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "srand",
        constants$15.const$0
    );
}


