// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

final class constants$102 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$102() {}
    static final VarHandle const$0 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("channelCount"));
    static final VarHandle const$1 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("incomingBandwidth"));
    static final VarHandle const$2 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("outgoingBandwidth"));
    static final VarHandle const$3 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("incomingBandwidthThrottleEpoch"));
    static final VarHandle const$4 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("outgoingBandwidthThrottleEpoch"));
    static final VarHandle const$5 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("incomingDataTotal"));
}


