// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

final class constants$72 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$72() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "unlinkat",
        constants$43.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rmdir",
        constants$2.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "tcgetpgrp",
        constants$23.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "tcsetpgrp",
        constants$46.const$5
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(RuntimeHelper.POINTER);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getlogin",
        constants$72.const$4
    );
}


