// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.MemoryLayout;
import java.lang.invoke.VarHandle;

final class constants$19 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$19() {}

  static final VarHandle const$0 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("reliableSequenceNumber"));
  static final VarHandle const$1 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("unreliableSequenceNumber"));
  static final VarHandle const$2 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("fragmentCount"));
  static final VarHandle const$3 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("fragmentsRemaining"));
  static final VarHandle const$4 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("fragments"));
  static final VarHandle const$5 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("packet"));
}


