// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.MemoryLayout;
import java.lang.invoke.VarHandle;

final class constants$34 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$34() {}

  static final VarHandle const$0 = constants$32.const$5.varHandle(MemoryLayout.PathElement.groupElement("recalculateBandwidthLimits"));
  static final VarHandle const$1 = constants$32.const$5.varHandle(MemoryLayout.PathElement.groupElement("peers"));
  static final VarHandle const$2 = constants$32.const$5.varHandle(MemoryLayout.PathElement.groupElement("peerCount"));
  static final VarHandle const$3 = constants$32.const$5.varHandle(MemoryLayout.PathElement.groupElement("channelLimit"));
  static final VarHandle const$4 = constants$32.const$5.varHandle(MemoryLayout.PathElement.groupElement("serviceTime"));
  static final VarHandle const$5 = constants$32.const$5.varHandle(MemoryLayout.PathElement.groupElement("continueSending"));
}


