// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemoryLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$30 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$30() {}

  static final VarHandle const$0 = constants$29.const$5.varHandle(MemoryLayout.PathElement.groupElement("context"));
  static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_LONG,
    RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
    JAVA_LONG,
    JAVA_LONG,
    RuntimeHelper.POINTER,
    JAVA_LONG
    );
  static final MethodHandle const$2 = RuntimeHelper.upcallHandle(_ENetCompressor.compress.class, "apply", constants$30.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
      constants$30.const$1
    );
  static final VarHandle const$4 = constants$29.const$5.varHandle(MemoryLayout.PathElement.groupElement("compress"));
  static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_LONG,
    RuntimeHelper.POINTER,
    RuntimeHelper.POINTER,
    JAVA_LONG,
    RuntimeHelper.POINTER,
    JAVA_LONG
    );
}


