// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$16 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$16() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("fptr"),
        RuntimeHelper.POINTER.withName("rptr"),
        RuntimeHelper.POINTER.withName("state"),
        JAVA_INT.withName("rand_type"),
        JAVA_INT.withName("rand_deg"),
        JAVA_INT.withName("rand_sep"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("end_ptr")
    ).withName("random_data");
    static final VarHandle const$1 = constants$16.const$0.varHandle(MemoryLayout.PathElement.groupElement("fptr"));
    static final VarHandle const$2 = constants$16.const$0.varHandle(MemoryLayout.PathElement.groupElement("rptr"));
    static final VarHandle const$3 = constants$16.const$0.varHandle(MemoryLayout.PathElement.groupElement("state"));
    static final VarHandle const$4 = constants$16.const$0.varHandle(MemoryLayout.PathElement.groupElement("rand_type"));
    static final VarHandle const$5 = constants$16.const$0.varHandle(MemoryLayout.PathElement.groupElement("rand_deg"));
}


