// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$47 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$47() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "accept",
        constants$37.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "shutdown",
        constants$46.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "sockatmark",
        constants$23.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "isfdtype",
        constants$46.const$5
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("s_addr")
    ).withName("in_addr");
    static final VarHandle const$5 = constants$47.const$4.varHandle(MemoryLayout.PathElement.groupElement("s_addr"));
}


