// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.MemoryLayout;
import java.lang.foreign.StructLayout;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.JAVA_BYTE;
import static java.lang.foreign.ValueLayout.JAVA_INT;
final class constants$37 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$37() {}

  static final VarHandle const$0 = constants$32.const$5.varHandle(MemoryLayout.PathElement.groupElement("connectedPeers"));
  static final VarHandle const$1 = constants$32.const$5.varHandle(MemoryLayout.PathElement.groupElement("bandwidthLimitedPeers"));
  static final VarHandle const$2 = constants$32.const$5.varHandle(MemoryLayout.PathElement.groupElement("duplicatePeers"));
  static final VarHandle const$3 = constants$32.const$5.varHandle(MemoryLayout.PathElement.groupElement("maximumPacketSize"));
  static final VarHandle const$4 = constants$32.const$5.varHandle(MemoryLayout.PathElement.groupElement("maximumWaitingData"));
  static final StructLayout const$5 = MemoryLayout.structLayout(
    JAVA_INT.withName("type"),
    MemoryLayout.paddingLayout(4),
    RuntimeHelper.POINTER.withName("peer"),
    JAVA_BYTE.withName("channelID"),
    MemoryLayout.paddingLayout(3),
    JAVA_INT.withName("data"),
    RuntimeHelper.POINTER.withName("packet")
  ).withName("_ENetEvent");
}


