// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$39 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$39() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_SHORT.withName("ss_family"),
        MemoryLayout.sequenceLayout(118, JAVA_BYTE).withName("__ss_padding"),
        JAVA_LONG.withName("__ss_align")
    ).withName("sockaddr_storage");
    static final VarHandle const$1 = constants$39.const$0.varHandle(MemoryLayout.PathElement.groupElement("ss_family"));
    static final VarHandle const$2 = constants$39.const$0.varHandle(MemoryLayout.PathElement.groupElement("__ss_align"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("msg_name"),
        JAVA_INT.withName("msg_namelen"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("msg_iov"),
        JAVA_LONG.withName("msg_iovlen"),
        RuntimeHelper.POINTER.withName("msg_control"),
        JAVA_LONG.withName("msg_controllen"),
        JAVA_INT.withName("msg_flags"),
        MemoryLayout.paddingLayout(4)
    ).withName("msghdr");
    static final VarHandle const$4 = constants$39.const$3.varHandle(MemoryLayout.PathElement.groupElement("msg_name"));
    static final VarHandle const$5 = constants$39.const$3.varHandle(MemoryLayout.PathElement.groupElement("msg_namelen"));
}


