// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$122 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$122() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "enet_packet_create",
        constants$122.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "enet_packet_destroy",
        constants$20.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "enet_packet_resize",
        constants$34.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "enet_crc32",
        constants$34.const$1
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "enet_host_create",
        constants$122.const$5
    );
}


