// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$37 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$37() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_usec")
        ).withName("it_interval"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_usec")
        ).withName("it_value")
    ).withName("itimerval");
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getitimer",
        constants$17.const$4
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "setitimer",
        constants$37.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "utimes",
        constants$17.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "lutimes",
        constants$17.const$2
    );
}


