// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$45 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$45() {}

  static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
    JAVA_LONG,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
      "enet_host_create",
        constants$45.const$0
    );
  static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
    "enet_host_destroy",
    constants$11.const$1
  );
  static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
    RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT
    );
  static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
    "enet_host_connect",
    constants$45.const$3
  );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
      "enet_host_check_events",
      constants$32.const$2
    );
}


