// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

final class constants$114 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$114() {}
    static final VarHandle const$0 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("headerFlags"));
    static final VarHandle const$1 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("commandCount"));
    static final VarHandle const$2 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("bufferCount"));
    static final VarHandle const$3 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("checksum"));
    static final VarHandle const$4 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("receivedData"));
    static final VarHandle const$5 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("receivedDataLength"));
}


