// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$7 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$7() {}
    static final UnionLayout const$0 = MemoryLayout.unionLayout(
        JAVA_LONG.withName("__value64"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("__low"),
            JAVA_INT.withName("__high")
        ).withName("__value32")
    ).withName("");
    static final VarHandle const$1 = constants$7.const$0.varHandle(MemoryLayout.PathElement.groupElement("__value64"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("__low"),
        JAVA_INT.withName("__high")
    ).withName("");
    static final VarHandle const$3 = constants$7.const$2.varHandle(MemoryLayout.PathElement.groupElement("__low"));
    static final VarHandle const$4 = constants$7.const$2.varHandle(MemoryLayout.PathElement.groupElement("__high"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("__prev"),
        RuntimeHelper.POINTER.withName("__next")
    ).withName("__pthread_internal_list");
}


