// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$121 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$121() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "enet_socketset_select",
        constants$121.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "enet_address_set_host_ip",
        constants$17.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "enet_address_set_host",
        constants$17.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "enet_address_get_host_ip",
        constants$34.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "enet_address_get_host",
        constants$34.const$3
    );
}


