// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

final class constants$115 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$115() {}
    static final VarHandle const$0 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("totalSentData"));
    static final VarHandle const$1 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("totalSentPackets"));
    static final VarHandle const$2 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("totalReceivedData"));
    static final VarHandle const$3 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("totalReceivedPackets"));
    static final VarHandle const$4 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("intercept"));
    static final VarHandle const$5 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("connectedPeers"));
}


