// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$44 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$44() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
      "enet_address_get_host",
      constants$43.const$4
    );
  static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT
    );
  static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
    "enet_packet_create",
    constants$44.const$1
  );
  static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
    "enet_packet_destroy",
    constants$11.const$1
  );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
      "enet_packet_resize",
      constants$31.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
      "enet_crc32",
      constants$31.const$5
    );
}


