// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

final class constants$83 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$83() {}
    static final VarHandle const$0 = constants$82.const$0.varHandle(MemoryLayout.PathElement.groupElement("channelCount"));
    static final VarHandle const$1 = constants$82.const$0.varHandle(MemoryLayout.PathElement.groupElement("incomingBandwidth"));
    static final VarHandle const$2 = constants$82.const$0.varHandle(MemoryLayout.PathElement.groupElement("outgoingBandwidth"));
    static final VarHandle const$3 = constants$82.const$0.varHandle(MemoryLayout.PathElement.groupElement("packetThrottleInterval"));
    static final VarHandle const$4 = constants$82.const$0.varHandle(MemoryLayout.PathElement.groupElement("packetThrottleAcceleration"));
    static final VarHandle const$5 = constants$82.const$0.varHandle(MemoryLayout.PathElement.groupElement("packetThrottleDeceleration"));
}


