// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

final class constants$104 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$104() {}
    static final VarHandle const$0 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("packetsSent"));
    static final VarHandle const$1 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("packetsLost"));
    static final VarHandle const$2 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("packetLoss"));
    static final VarHandle const$3 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("packetLossVariance"));
    static final VarHandle const$4 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("packetThrottle"));
    static final VarHandle const$5 = constants$100.const$2.varHandle(MemoryLayout.PathElement.groupElement("packetThrottleLimit"));
}


