// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;

final class constants$127 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$127() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "enet_peer_reset",
        constants$20.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "enet_peer_disconnect",
        constants$126.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "enet_peer_disconnect_now",
        constants$126.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "enet_peer_disconnect_later",
        constants$126.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "enet_peer_throttle_configure",
        constants$126.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "enet_peer_throttle",
        constants$29.const$4
    );
}


