// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$130 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$130() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "enet_peer_on_disconnect",
        constants$20.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "enet_range_coder_create",
        constants$72.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "enet_range_coder_destroy",
        constants$20.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "enet_range_coder_compress",
        constants$109.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "enet_range_coder_decompress",
        constants$110.const$1
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_BYTE
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "enet_protocol_command_size",
        constants$130.const$5
    );
}


