// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$99 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$99() {}
    static final VarHandle const$0 = constants$98.const$1.varHandle(MemoryLayout.PathElement.groupElement("fragments"));
    static final VarHandle const$1 = constants$98.const$1.varHandle(MemoryLayout.PathElement.groupElement("packet"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_SHORT.withName("outgoingReliableSequenceNumber"),
        JAVA_SHORT.withName("outgoingUnreliableSequenceNumber"),
        JAVA_SHORT.withName("usedReliableWindows"),
        MemoryLayout.sequenceLayout(16, JAVA_SHORT).withName("reliableWindows"),
        JAVA_SHORT.withName("incomingReliableSequenceNumber"),
        JAVA_SHORT.withName("incomingUnreliableSequenceNumber"),
        MemoryLayout.paddingLayout(6),
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("next"),
                RuntimeHelper.POINTER.withName("previous")
            ).withName("sentinel")
        ).withName("incomingReliableCommands"),
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("next"),
                RuntimeHelper.POINTER.withName("previous")
            ).withName("sentinel")
        ).withName("incomingUnreliableCommands")
    ).withName("_ENetChannel");
    static final VarHandle const$3 = constants$99.const$2.varHandle(MemoryLayout.PathElement.groupElement("outgoingReliableSequenceNumber"));
    static final VarHandle const$4 = constants$99.const$2.varHandle(MemoryLayout.PathElement.groupElement("outgoingUnreliableSequenceNumber"));
    static final VarHandle const$5 = constants$99.const$2.varHandle(MemoryLayout.PathElement.groupElement("usedReliableWindows"));
}


