// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$86 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$86() {}
    static final VarHandle const$0 = constants$84.const$2.varHandle(MemoryLayout.PathElement.groupElement("packetThrottleAcceleration"));
    static final VarHandle const$1 = constants$84.const$2.varHandle(MemoryLayout.PathElement.groupElement("packetThrottleDeceleration"));
    static final VarHandle const$2 = constants$84.const$2.varHandle(MemoryLayout.PathElement.groupElement("connectID"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("command"),
            JAVA_BYTE.withName("channelID"),
            JAVA_SHORT.withByteAlignment(1).withName("reliableSequenceNumber")
        ).withName("header"),
        JAVA_INT.withByteAlignment(1).withName("incomingBandwidth"),
        JAVA_INT.withByteAlignment(1).withName("outgoingBandwidth")
    ).withName("_ENetProtocolBandwidthLimit");
    static final VarHandle const$4 = constants$86.const$3.varHandle(MemoryLayout.PathElement.groupElement("incomingBandwidth"));
    static final VarHandle const$5 = constants$86.const$3.varHandle(MemoryLayout.PathElement.groupElement("outgoingBandwidth"));
}


