// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

final class constants$113 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$113() {}
    static final VarHandle const$0 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("peers"));
    static final VarHandle const$1 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("peerCount"));
    static final VarHandle const$2 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("channelLimit"));
    static final VarHandle const$3 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("serviceTime"));
    static final VarHandle const$4 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("continueSending"));
    static final VarHandle const$5 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("packetSize"));
}


