// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$88 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$88() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("command"),
            JAVA_BYTE.withName("channelID"),
            JAVA_SHORT.withByteAlignment(1).withName("reliableSequenceNumber")
        ).withName("header")
    ).withName("_ENetProtocolPing");
    static final StructLayout const$1 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("command"),
            JAVA_BYTE.withName("channelID"),
            JAVA_SHORT.withByteAlignment(1).withName("reliableSequenceNumber")
        ).withName("header"),
        JAVA_SHORT.withByteAlignment(1).withName("dataLength")
    ).withName("_ENetProtocolSendReliable");
    static final VarHandle const$2 = constants$88.const$1.varHandle(MemoryLayout.PathElement.groupElement("dataLength"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("command"),
            JAVA_BYTE.withName("channelID"),
            JAVA_SHORT.withByteAlignment(1).withName("reliableSequenceNumber")
        ).withName("header"),
        JAVA_SHORT.withByteAlignment(1).withName("unreliableSequenceNumber"),
        JAVA_SHORT.withByteAlignment(1).withName("dataLength")
    ).withName("_ENetProtocolSendUnreliable");
    static final VarHandle const$4 = constants$88.const$3.varHandle(MemoryLayout.PathElement.groupElement("unreliableSequenceNumber"));
    static final VarHandle const$5 = constants$88.const$3.varHandle(MemoryLayout.PathElement.groupElement("dataLength"));
}


