// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$124 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$124() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_BYTE,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "enet_host_broadcast",
        constants$124.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "enet_host_compress",
        constants$124.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "enet_host_compress_with_range_coder",
        constants$2.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "enet_host_channel_limit",
        constants$23.const$3
    );
}


