// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$81 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$81() {}
    static final VarHandle const$0 = constants$80.const$5.varHandle(MemoryLayout.PathElement.groupElement("command"));
    static final VarHandle const$1 = constants$80.const$5.varHandle(MemoryLayout.PathElement.groupElement("channelID"));
    static final VarHandle const$2 = constants$80.const$5.varHandle(MemoryLayout.PathElement.groupElement("reliableSequenceNumber"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("command"),
            JAVA_BYTE.withName("channelID"),
            JAVA_SHORT.withByteAlignment(1).withName("reliableSequenceNumber")
        ).withName("header"),
        JAVA_SHORT.withByteAlignment(1).withName("receivedReliableSequenceNumber"),
        JAVA_SHORT.withByteAlignment(1).withName("receivedSentTime")
    ).withName("_ENetProtocolAcknowledge");
    static final VarHandle const$4 = constants$81.const$3.varHandle(MemoryLayout.PathElement.groupElement("receivedReliableSequenceNumber"));
    static final VarHandle const$5 = constants$81.const$3.varHandle(MemoryLayout.PathElement.groupElement("receivedSentTime"));
}


