// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetProtocolConnect ENetProtocolConnect;
 * }
 */
public final class ENetProtocolConnect extends _ENetProtocolConnect {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetProtocolConnect() {}
}


