// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetProtocolBandwidthLimit ENetProtocolBandwidthLimit;
 * }
 */
public final class ENetProtocolBandwidthLimit extends _ENetProtocolBandwidthLimit {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetProtocolBandwidthLimit() {}
}


