// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetProtocolSendReliable ENetProtocolSendReliable;
 * }
 */
public final class ENetProtocolSendReliable extends _ENetProtocolSendReliable {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetProtocolSendReliable() {}
}


