// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetProtocolAcknowledge ENetProtocolAcknowledge;
 * }
 */
public final class ENetProtocolAcknowledge extends _ENetProtocolAcknowledge {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetProtocolAcknowledge() {}
}


