// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetHost ENetHost;
 * }
 */
public final class ENetHost extends _ENetHost {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetHost() {}
}


