// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetAddress ENetAddress;
 * }
 */
public final class ENetAddress extends _ENetAddress {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetAddress() {}
}


