// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetIncomingCommand ENetIncomingCommand;
 * }
 */
public final class ENetIncomingCommand extends _ENetIncomingCommand {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetIncomingCommand() {}
}


