// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetChannel ENetChannel;
 * }
 */
public final class ENetChannel extends _ENetChannel {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetChannel() {}
}


