// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct {
 *     void* data;
 *     size_t dataLength;
 * };
 * }
 */
public class ENetBuffer {

    public static MemoryLayout $LAYOUT() {
        return constants$79.const$5;
    }
    public static VarHandle data$VH() {
        return constants$80.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* data;
     * }
     */
    public static MemorySegment data$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$80.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* data;
     * }
     */
    public static void data$set(MemorySegment seg, MemorySegment x) {
        constants$80.const$0.set(seg, x);
    }
    public static MemorySegment data$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$80.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void data$set(MemorySegment seg, long index, MemorySegment x) {
        constants$80.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle dataLength$VH() {
        return constants$80.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * size_t dataLength;
     * }
     */
    public static long dataLength$get(MemorySegment seg) {
        return (long)constants$80.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * size_t dataLength;
     * }
     */
    public static void dataLength$set(MemorySegment seg, long x) {
        constants$80.const$1.set(seg, x);
    }
    public static long dataLength$get(MemorySegment seg, long index) {
        return (long)constants$80.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void dataLength$set(MemorySegment seg, long index, long x) {
        constants$80.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


