// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetCallbacks ENetCallbacks;
 * }
 */
public final class ENetCallbacks extends _ENetCallbacks {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetCallbacks() {}
}


