// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetProtocolSendUnreliable ENetProtocolSendUnreliable;
 * }
 */
public final class ENetProtocolSendUnreliable extends _ENetProtocolSendUnreliable {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetProtocolSendUnreliable() {}
}


