// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetAcknowledgement ENetAcknowledgement;
 * }
 */
public final class ENetAcknowledgement extends _ENetAcknowledgement {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetAcknowledgement() {}
}


