// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetProtocolPing ENetProtocolPing;
 * }
 */
public final class ENetProtocolPing extends _ENetProtocolPing {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetProtocolPing() {}
}


