// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetPacket ENetPacket;
 * }
 */
public final class ENetPacket extends _ENetPacket {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetPacket() {}
}


