// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef union _ENetProtocol ENetProtocol;
 * }
 */
public final class ENetProtocol extends _ENetProtocol {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetProtocol() {}
}


