// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetList ENetList;
 * }
 */
public final class ENetList extends _ENetList {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetList() {}
}


