// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetProtocolSendFragment ENetProtocolSendFragment;
 * }
 */
public final class ENetProtocolSendFragment extends _ENetProtocolSendFragment {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetProtocolSendFragment() {}
}


