// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetCompressor ENetCompressor;
 * }
 */
public final class ENetCompressor extends _ENetCompressor {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetCompressor() {}
}


