// Generated by jextract

package com.juanmuscaria.foreign.enet;

/**
 * {@snippet :
 * typedef struct _ENetListNode ENetListNode;
 * }
 */
public final class ENetListNode extends _ENetListNode {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENetListNode() {}
}


