// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct in_pktinfo {
 *     int ipi_ifindex;
 *     struct in_addr ipi_spec_dst;
 *     struct in_addr ipi_addr;
 * };
 * }
 */
public class in_pktinfo {

    public static MemoryLayout $LAYOUT() {
        return constants$48.const$1;
    }
    public static VarHandle ipi_ifindex$VH() {
        return constants$48.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int ipi_ifindex;
     * }
     */
    public static int ipi_ifindex$get(MemorySegment seg) {
        return (int)constants$48.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int ipi_ifindex;
     * }
     */
    public static void ipi_ifindex$set(MemorySegment seg, int x) {
        constants$48.const$2.set(seg, x);
    }
    public static int ipi_ifindex$get(MemorySegment seg, long index) {
        return (int)constants$48.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void ipi_ifindex$set(MemorySegment seg, long index, int x) {
        constants$48.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment ipi_spec_dst$slice(MemorySegment seg) {
        return seg.asSlice(4, 4);
    }
    public static MemorySegment ipi_addr$slice(MemorySegment seg) {
        return seg.asSlice(8, 4);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


