// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct iovec {
 *     void* iov_base;
 *     size_t iov_len;
 * };
 * }
 */
public class iovec {

    public static MemoryLayout $LAYOUT() {
        return constants$38.const$1;
    }
    public static VarHandle iov_base$VH() {
        return constants$38.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* iov_base;
     * }
     */
    public static MemorySegment iov_base$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$38.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* iov_base;
     * }
     */
    public static void iov_base$set(MemorySegment seg, MemorySegment x) {
        constants$38.const$2.set(seg, x);
    }
    public static MemorySegment iov_base$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$38.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void iov_base$set(MemorySegment seg, long index, MemorySegment x) {
        constants$38.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle iov_len$VH() {
        return constants$38.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * size_t iov_len;
     * }
     */
    public static long iov_len$get(MemorySegment seg) {
        return (long)constants$38.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * size_t iov_len;
     * }
     */
    public static void iov_len$set(MemorySegment seg, long x) {
        constants$38.const$3.set(seg, x);
    }
    public static long iov_len$get(MemorySegment seg, long index) {
        return (long)constants$38.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void iov_len$set(MemorySegment seg, long index, long x) {
        constants$38.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


