// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct ipv6_mreq {
 *     struct in6_addr ipv6mr_multiaddr;
 *     unsigned int ipv6mr_interface;
 * };
 * }
 */
public class ipv6_mreq {

    public static MemoryLayout $LAYOUT() {
        return constants$51.const$1;
    }
    public static MemorySegment ipv6mr_multiaddr$slice(MemorySegment seg) {
        return seg.asSlice(0, 16);
    }
    public static VarHandle ipv6mr_interface$VH() {
        return constants$51.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int ipv6mr_interface;
     * }
     */
    public static int ipv6mr_interface$get(MemorySegment seg) {
        return (int)constants$51.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int ipv6mr_interface;
     * }
     */
    public static void ipv6mr_interface$set(MemorySegment seg, int x) {
        constants$51.const$2.set(seg, x);
    }
    public static int ipv6mr_interface$get(MemorySegment seg, long index) {
        return (int)constants$51.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void ipv6mr_interface$set(MemorySegment seg, long index, int x) {
        constants$51.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


