// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct {
 *     long quot;
 *     long rem;
 * };
 * }
 */
public class ldiv_t {

    public static MemoryLayout $LAYOUT() {
        return constants$0.const$3;
    }
    public static VarHandle quot$VH() {
        return constants$0.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * long quot;
     * }
     */
    public static long quot$get(MemorySegment seg) {
        return (long)constants$0.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * long quot;
     * }
     */
    public static void quot$set(MemorySegment seg, long x) {
        constants$0.const$4.set(seg, x);
    }
    public static long quot$get(MemorySegment seg, long index) {
        return (long)constants$0.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void quot$set(MemorySegment seg, long index, long x) {
        constants$0.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle rem$VH() {
        return constants$0.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * long rem;
     * }
     */
    public static long rem$get(MemorySegment seg) {
        return (long)constants$0.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * long rem;
     * }
     */
    public static void rem$set(MemorySegment seg, long x) {
        constants$0.const$5.set(seg, x);
    }
    public static long rem$get(MemorySegment seg, long index) {
        return (long)constants$0.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void rem$set(MemorySegment seg, long index, long x) {
        constants$0.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


