// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct linger {
 *     int l_onoff;
 *     int l_linger;
 * };
 * }
 */
public class linger {

    public static MemoryLayout $LAYOUT() {
        return constants$42.const$2;
    }
    public static VarHandle l_onoff$VH() {
        return constants$42.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int l_onoff;
     * }
     */
    public static int l_onoff$get(MemorySegment seg) {
        return (int)constants$42.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int l_onoff;
     * }
     */
    public static void l_onoff$set(MemorySegment seg, int x) {
        constants$42.const$3.set(seg, x);
    }
    public static int l_onoff$get(MemorySegment seg, long index) {
        return (int)constants$42.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void l_onoff$set(MemorySegment seg, long index, int x) {
        constants$42.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle l_linger$VH() {
        return constants$42.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int l_linger;
     * }
     */
    public static int l_linger$get(MemorySegment seg) {
        return (int)constants$42.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int l_linger;
     * }
     */
    public static void l_linger$set(MemorySegment seg, int x) {
        constants$42.const$4.set(seg, x);
    }
    public static int l_linger$get(MemorySegment seg, long index) {
        return (int)constants$42.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void l_linger$set(MemorySegment seg, long index, int x) {
        constants$42.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


