// Generated by jextract

package com.juanmuscaria.foreign.enet;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct timezone {
 *     int tz_minuteswest;
 *     int tz_dsttime;
 * };
 * }
 */
public class timezone {

    public static MemoryLayout $LAYOUT() {
        return constants$36.const$0;
    }
    public static VarHandle tz_minuteswest$VH() {
        return constants$36.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int tz_minuteswest;
     * }
     */
    public static int tz_minuteswest$get(MemorySegment seg) {
        return (int)constants$36.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int tz_minuteswest;
     * }
     */
    public static void tz_minuteswest$set(MemorySegment seg, int x) {
        constants$36.const$1.set(seg, x);
    }
    public static int tz_minuteswest$get(MemorySegment seg, long index) {
        return (int)constants$36.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void tz_minuteswest$set(MemorySegment seg, long index, int x) {
        constants$36.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle tz_dsttime$VH() {
        return constants$36.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int tz_dsttime;
     * }
     */
    public static int tz_dsttime$get(MemorySegment seg) {
        return (int)constants$36.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int tz_dsttime;
     * }
     */
    public static void tz_dsttime$set(MemorySegment seg, int x) {
        constants$36.const$2.set(seg, x);
    }
    public static int tz_dsttime$get(MemorySegment seg, long index) {
        return (int)constants$36.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void tz_dsttime$set(MemorySegment seg, long index, int x) {
        constants$36.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


