package io.github.juanmuscaria.blockheads.jna.enet.structures;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import io.github.juanmuscaria.blockheads.jna.types.Uint16_t;
import io.github.juanmuscaria.blockheads.jna.types.Uint32_t;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : enet/enet.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ENetAddress extends Structure {
	/** C type : enet_uint32 */
	public Uint32_t host;
	/** C type : enet_uint16 */
	public Uint16_t port;
	public ENetAddress() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("host", "port");
	}
	/**
	 * @param host C type : enet_uint32<br>
	 * @param port C type : enet_uint16
	 */
	public ENetAddress(Uint32_t host, Uint16_t port) {
		super();
		this.host = host;
		this.port = port;
	}
	public ENetAddress(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ENetAddress implements Structure.ByReference {
		
	}

    public static class ByValue extends ENetAddress implements Structure.ByValue {
		
	}
}
