package io.github.juanmuscaria.blockheads.jna.enet.structures;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : ./enet/protocol.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ENetProtocolSendFragment extends Structure {
	/** C type : ENetProtocolCommandHeader */
	public ENetProtocolCommandHeader header;
	/** C type : enet_uint16 */
	public short startSequenceNumber;
	/** C type : enet_uint16 */
	public short dataLength;
	/** C type : enet_uint32 */
	public int fragmentCount;
	/** C type : enet_uint32 */
	public int fragmentNumber;
	/** C type : enet_uint32 */
	public int totalLength;
	/** C type : enet_uint32 */
	public int fragmentOffset;
	public ENetProtocolSendFragment() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("header", "startSequenceNumber", "dataLength", "fragmentCount", "fragmentNumber", "totalLength", "fragmentOffset");
	}
	/**
	 * @param header C type : ENetProtocolCommandHeader<br>
	 * @param startSequenceNumber C type : enet_uint16<br>
	 * @param dataLength C type : enet_uint16<br>
	 * @param fragmentCount C type : enet_uint32<br>
	 * @param fragmentNumber C type : enet_uint32<br>
	 * @param totalLength C type : enet_uint32<br>
	 * @param fragmentOffset C type : enet_uint32
	 */
	public ENetProtocolSendFragment(ENetProtocolCommandHeader header, short startSequenceNumber, short dataLength, int fragmentCount, int fragmentNumber, int totalLength, int fragmentOffset) {
		super();
		this.header = header;
		this.startSequenceNumber = startSequenceNumber;
		this.dataLength = dataLength;
		this.fragmentCount = fragmentCount;
		this.fragmentNumber = fragmentNumber;
		this.totalLength = totalLength;
		this.fragmentOffset = fragmentOffset;
	}
	public ENetProtocolSendFragment(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ENetProtocolSendFragment implements Structure.ByReference {
		
	}

	public static class ByValue extends ENetProtocolSendFragment implements Structure.ByValue {
		
	}
}
